# Name of workflow
name: Test CI Allearning

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  build: # имя взято для примера
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v3
      # Устанавливаем Node.js
      - uses: actions/setup-node@v1
        with:
          cache: 'npm'
      # Ставим зависимости
      - run: make setup
      # Запускаем линтер
      - run: make lint
      # Запускаем тесты
      # у шагов может быть имя, иногда это помогает отладке
      # имя выводится на Github при просмотре сборки
      - name: run tests
        run: make test # name и run относятся к одной задаче, поэтому дефис ставится толь
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: 6c3f158a-3515-43c0-a5c2-e47ddd198c3e